# Generated by Django 5.1.3 on 2024-11-12 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Тема')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата обращения')),
                ('client', models.EmailField(max_length=256, verbose_name='От кого')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
        ),
    ]
